In [111]:
a=[1,2,3,4,5,6]
#a**2 genrates an error as no use of pow b/w list and number

In [112]:
import numpy as np

In [113]:
b=np.array(a,dtype=np.int16,ndmin=3) #b is an array with dimensions 3, and dtype is specified as int16

In [114]:
b**2 #Each element of b is raised to the power of 2

array([[[ 1,  4,  9, 16, 25, 36]]], dtype=int16)

In [115]:
b

array([[[1, 2, 3, 4, 5, 6]]], dtype=int16)

In [116]:
b.shape,b.ndim,b.dtype,b.itemsize #Displaying the shape,dimensions and dtype of b array

((1, 1, 6), 3, dtype('int16'), 2)

In [117]:
b.shape=(3,2,1) #Changing the shape of array b

In [118]:
b

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int16)

In [119]:
b=np.arange(1,10,0.1) 
b #Gives a 1D array with numbers ranging from 1 to 10 at an interval of 0.1

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [120]:
b=np.linspace(1,10,10)
10**b

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [121]:
9/49

0.1836734693877551

In [122]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [123]:
np.empty((2,3))

array([[4.94065646e-324, 0.00000000e+000, 2.12199579e-314],
       [0.00000000e+000, 2.12199579e-314, 4.94065646e-324]])

In [124]:
np.zeros((2,2)) #2D array or 2x2 matrix with zeros as elements

array([[0., 0.],
       [0., 0.]])

In [125]:
np.ones((2,2)) #2D array or 2x2 matrix with ones as elements

array([[1., 1.],
       [1., 1.]])

In [126]:
a=np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [127]:
a.shape=(2,2,2,2) #Changing the shape
np.reshape(a,(2,2,2,2,1)) #Another way of changing the shape
#The shape of the array should be changed in such a way that the number of elements renain the same

array([[[[[ 1],
          [ 2]],

         [[ 3],
          [ 4]]],


        [[[ 5],
          [ 6]],

         [[ 7],
          [ 8]]]],



       [[[[ 9],
          [10]],

         [[11],
          [12]]],


        [[[13],
          [14]],

         [[15],
          [16]]]]])

In [128]:
np.resize(a,(4,3,2)) #Changing the shape of a with resize
#With resize, the number of elements need not be the same. The elements may get repeated according to the dimensions

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [ 1,  2]],

       [[ 3,  4],
        [ 5,  6],
        [ 7,  8]]])

In [129]:
a.T
np.transpose(a)

array([[[[ 1,  9],
         [ 5, 13]],

        [[ 3, 11],
         [ 7, 15]]],


       [[[ 2, 10],
         [ 6, 14]],

        [[ 4, 12],
         [ 8, 16]]]])

In [130]:
a.shape=(4,1,2,1,2)
a.T.shape

(2, 1, 2, 1, 4)

In [131]:
np.swapaxes(a,1,4).shape #2 axes are swapped ie at indices 1 and 4 which are values 1 and 2 respectively 

(4, 2, 2, 1, 1)

In [132]:
np.rollaxis(a,4,1).shape 

(4, 2, 1, 2, 1)

In [133]:
a.flatten(),np.ravel(a) #To convert an array into a 1D array

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]))

In [134]:
from functools import reduce
np.reshape(a,reduce(lambda x,y:x*y,a.shape))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [135]:
list(a.flat) #Gives a list of flattened array a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [136]:
a.shape=(4,4)

In [137]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [138]:
a[2::-1,::2]

array([[ 9, 11],
       [ 5,  7],
       [ 1,  3]])

In [139]:
a[[0,1,3],1]


array([ 2,  6, 14])

In [140]:
a[np.bitwise_and((a%2==0),(a!=4))] #gives the elements of array a that satisfy both the given conditions

array([ 2,  6,  8, 10, 12, 14, 16])

In [141]:
b=np.arange(100,116)

In [142]:
b.shape=(4,4)

In [143]:
for i in np.nditer((a,b),order='F'):
    print(i,end= ' ')

(array(1), array(100)) (array(5), array(104)) (array(9), array(108)) (array(13), array(112)) (array(2), array(101)) (array(6), array(105)) (array(10), array(109)) (array(14), array(113)) (array(3), array(102)) (array(7), array(106)) (array(11), array(110)) (array(15), array(114)) (array(4), array(103)) (array(8), array(107)) (array(12), array(111)) (array(16), array(115)) 

In [144]:
b.ndim

2

In [145]:
c=np.expand_dims(b,2)
c.shape

(4, 4, 1)

In [146]:
np.squeeze(c,2).shape

(4, 4)

In [147]:
np.concatenate((a,b),axis=0) #Concatenates 2 arrays row wise

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])

In [148]:
np.concatenate((a,b),axis=1) #Concatenates 2 arrays column wise

array([[  1,   2,   3,   4, 100, 101, 102, 103],
       [  5,   6,   7,   8, 104, 105, 106, 107],
       [  9,  10,  11,  12, 108, 109, 110, 111],
       [ 13,  14,  15,  16, 112, 113, 114, 115]])

In [149]:
np.stack((a,b),axis=0).shape,np.stack((a,b),axis=1).shape,np.stack((a,b),axis=2).shape

((2, 4, 4), (4, 2, 4), (4, 4, 2))

In [150]:
np.hstack((a,b)),np.vstack((a,b))

(array([[  1,   2,   3,   4, 100, 101, 102, 103],
        [  5,   6,   7,   8, 104, 105, 106, 107],
        [  9,  10,  11,  12, 108, 109, 110, 111],
        [ 13,  14,  15,  16, 112, 113, 114, 115]]),
 array([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111],
        [112, 113, 114, 115]]))

In [151]:
x,y=np.split(a,2,axis=1)
x.shape

(4, 2)

In [152]:
x

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [153]:
y

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [154]:
np.append(a,b,axis=1)

array([[  1,   2,   3,   4, 100, 101, 102, 103],
       [  5,   6,   7,   8, 104, 105, 106, 107],
       [  9,  10,  11,  12, 108, 109, 110, 111],
       [ 13,  14,  15,  16, 112, 113, 114, 115]])

In [155]:
np.insert(a,1,[12,34,56,78],axis=1)

array([[ 1, 12,  2,  3,  4],
       [ 5, 34,  6,  7,  8],
       [ 9, 56, 10, 11, 12],
       [13, 78, 14, 15, 16]])

In [156]:
np.delete(a,0,axis=1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [157]:
a=np.array(['a','b','a','c','b','d','a'])

In [158]:
np.unique(a)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [159]:
np.unique(a,return_counts=True)

(array(['a', 'b', 'c', 'd'], dtype='<U1'), array([3, 2, 1, 1], dtype=int64))

In [160]:
np.unique(a,return_index=True)

(array(['a', 'b', 'c', 'd'], dtype='<U1'), array([0, 1, 3, 5], dtype=int64))

In [161]:
np.unique(a,return_inverse=True)

(array(['a', 'b', 'c', 'd'], dtype='<U1'),
 array([0, 1, 0, 2, 1, 3, 0], dtype=int64))

In [162]:
a

array(['a', 'b', 'a', 'c', 'b', 'd', 'a'], dtype='<U1')

In [163]:
a=np.array([[1,34,222,34],[1234,5,678,4444],[12,4567,777,666]])

In [164]:
np.max(a,axis=0),np.max(a,axis=1),

(array([1234, 4567,  777, 4444]), array([ 222, 4444, 4567]))

In [165]:
a

array([[   1,   34,  222,   34],
       [1234,    5,  678, 4444],
       [  12, 4567,  777,  666]])

In [166]:
np.min(a,axis=0),np.min(a,axis=1),

(array([  1,   5, 222,  34]), array([ 1,  5, 12]))

In [167]:
np.mean(a,axis=0)

array([ 415.66666667, 1535.33333333,  559.        , 1714.66666667])

In [168]:
np.mean(a,axis=1)

array([  72.75, 1590.25, 1505.5 ])

In [169]:
np.ptp(a,axis=0),np.ptp(a,axis=1)

(array([1233, 4562,  555, 4410]), array([ 221, 4439, 4555]))

In [170]:
np.sort(a.flatten())

array([   1,    5,   12,   34,   34,  222,  666,  678,  777, 1234, 4444,
       4567])

In [171]:
np.percentile(a,50)

444.0

In [172]:
np.average(a,axis=0)

array([ 415.66666667, 1535.33333333,  559.        , 1714.66666667])

In [173]:
np.mean(a,axis=0)

array([ 415.66666667, 1535.33333333,  559.        , 1714.66666667])

In [174]:
np.sort(a,kind='quick',axis=0)

array([[   1,    5,  222,   34],
       [  12,   34,  678,  666],
       [1234, 4567,  777, 4444]])

In [175]:
a

array([[   1,   34,  222,   34],
       [1234,    5,  678, 4444],
       [  12, 4567,  777,  666]])

In [176]:
np.where(a%2,5,6)

array([[5, 6, 6, 6],
       [6, 5, 6, 6],
       [6, 5, 5, 6]])

In [177]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [178]:
np.multiply(a,4)
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [179]:
1/np.sin(a)

array([[ 1.18839511,  1.09975017],
       [ 7.0861674 , -1.32134871]])

In [180]:
from numpy import matlib

In [181]:
matlib.identity(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [182]:
matlib.eye(4,5,2)

matrix([[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [183]:
a=matlib.matrix([[1,2]])
b=matlib.matrix([[5,6]])
np.dot(a,b.T)

matrix([[17]])

In [184]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.linalg.norm(b)

13.19090595827292

In [185]:
np.sqrt(sum((a-b)**2))

array([5.65685425, 5.65685425])

In [186]:
np.linalg.norm(a-b)

8.0